databases:
  - name: db.sqlite3
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: root
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn root.asgi:application -k uvicorn.workers.UvicornWorker'
 